export const M_FACEBOOK_URL = "https://m.facebook.com/";
export const MBASIC_FACEBOOK_URL = "https://mbasic.facebook.com/";
export const MONICA_FACEBOOK_ADDRESS_NAME = "Facebook";
export const MONICA_FACEBOOK_NOTE_TITLE = "Facebook Info";

export const MONICA_COUNTRIES = {
  AFG: { id: "AF", object: "country", name: "Afghanistan", iso: "AF" },
  WSB: { id: "WSB", object: "country", name: "Akrotiri", iso: "WSB" },
  ALA: { id: "AX", object: "country", name: "\u00c5land Islands", iso: "AX" },
  ALB: { id: "AL", object: "country", name: "Albania", iso: "AL" },
  DZA: { id: "DZ", object: "country", name: "Algeria", iso: "DZ" },
  ASM: { id: "AS", object: "country", name: "American Samoa", iso: "AS" },
  AND: { id: "AD", object: "country", name: "Andorra", iso: "AD" },
  AGO: { id: "AO", object: "country", name: "Angola", iso: "AO" },
  AIA: { id: "AI", object: "country", name: "Anguilla", iso: "AI" },
  ATA: { id: "AQ", object: "country", name: "Antarctica", iso: "AQ" },
  ATG: {
    id: "AG",
    object: "country",
    name: "Antigua and Barbuda",
    iso: "AG",
  },
  ARG: { id: "AR", object: "country", name: "Argentina", iso: "AR" },
  ARM: { id: "AM", object: "country", name: "Armenia", iso: "AM" },
  ABW: { id: "AW", object: "country", name: "Aruba", iso: "AW" },
  ATC: {
    id: "ATC",
    object: "country",
    name: "Ashmore and Cartier Is.",
    iso: "ATC",
  },
  AUS: { id: "AU", object: "country", name: "Australia", iso: "AU" },
  AUT: { id: "AT", object: "country", name: "Austria", iso: "AT" },
  AZE: { id: "AZ", object: "country", name: "Azerbaijan", iso: "AZ" },
  BHS: { id: "BS", object: "country", name: "Bahamas", iso: "BS" },
  BHR: { id: "BH", object: "country", name: "Bahrain", iso: "BH" },
  KAB: { id: "KAB", object: "country", name: "Baikonur", iso: "KAB" },
  BJN: { id: "BJN", object: "country", name: "Bajo Nuevo Bank", iso: "BJN" },
  BGD: { id: "BD", object: "country", name: "Bangladesh", iso: "BD" },
  BRB: { id: "BB", object: "country", name: "Barbados", iso: "BB" },
  BLR: { id: "BY", object: "country", name: "Belarus", iso: "BY" },
  BEL: { id: "BE", object: "country", name: "Belgium", iso: "BE" },
  BLZ: { id: "BZ", object: "country", name: "Belize", iso: "BZ" },
  BEN: { id: "BJ", object: "country", name: "Benin", iso: "BJ" },
  BMU: { id: "BM", object: "country", name: "Bermuda", iso: "BM" },
  BTN: { id: "BT", object: "country", name: "Bhutan", iso: "BT" },
  BOL: { id: "BO", object: "country", name: "Bolivia", iso: "BO" },
  BIH: {
    id: "BA",
    object: "country",
    name: "Bosnia and Herzegovina",
    iso: "BA",
  },
  BWA: { id: "BW", object: "country", name: "Botswana", iso: "BW" },
  BVT: { id: "BV", object: "country", name: "Bouvet Island", iso: "BV" },
  BRA: { id: "BR", object: "country", name: "Brazil", iso: "BR" },
  IOT: {
    id: "IO",
    object: "country",
    name: "British Indian Ocean Territory",
    iso: "IO",
  },
  VGB: {
    id: "VG",
    object: "country",
    name: "British Virgin Islands",
    iso: "VG",
  },
  BRN: { id: "BN", object: "country", name: "Brunei", iso: "BN" },
  BGR: { id: "BG", object: "country", name: "Bulgaria", iso: "BG" },
  BFA: { id: "BF", object: "country", name: "Burkina Faso", iso: "BF" },
  BDI: { id: "BI", object: "country", name: "Burundi", iso: "BI" },
  KHM: { id: "KH", object: "country", name: "Cambodia", iso: "KH" },
  CMR: { id: "CM", object: "country", name: "Cameroon", iso: "CM" },
  CAN: { id: "CA", object: "country", name: "Canada", iso: "CA" },
  CPV: { id: "CV", object: "country", name: "Cape Verde", iso: "CV" },
  BES: {
    id: "BQ",
    object: "country",
    name: "Caribbean Netherlands",
    iso: "BQ",
  },
  CYM: { id: "KY", object: "country", name: "Cayman Islands", iso: "KY" },
  CAF: {
    id: "CF",
    object: "country",
    name: "Central African Republic",
    iso: "CF",
  },
  TCD: { id: "TD", object: "country", name: "Chad", iso: "TD" },
  CHL: { id: "CL", object: "country", name: "Chile", iso: "CL" },
  CHN: { id: "CN", object: "country", name: "China", iso: "CN" },
  CXR: { id: "CX", object: "country", name: "Christmas Island", iso: "CX" },
  CLP: { id: "CLP", object: "country", name: "Clipperton I.", iso: "CLP" },
  CCK: {
    id: "CC",
    object: "country",
    name: "Cocos (Keeling) Islands",
    iso: "CC",
  },
  COL: { id: "CO", object: "country", name: "Colombia", iso: "CO" },
  COM: { id: "KM", object: "country", name: "Comoros", iso: "KM" },
  COK: { id: "CK", object: "country", name: "Cook Islands", iso: "CK" },
  CSI: { id: "CSI", object: "country", name: "Coral Sea Is.", iso: "CSI" },
  CRI: { id: "CR", object: "country", name: "Costa Rica", iso: "CR" },
  HRV: { id: "HR", object: "country", name: "Croatia", iso: "HR" },
  CUB: { id: "CU", object: "country", name: "Cuba", iso: "CU" },
  CUW: { id: "CW", object: "country", name: "Cura\u00e7ao", iso: "CW" },
  CYP: { id: "CY", object: "country", name: "Cyprus", iso: "CY" },
  CNM: {
    id: "CNM",
    object: "country",
    name: "Cyprus U.N. Buffer Zone",
    iso: "CNM",
  },
  CZE: { id: "CZ", object: "country", name: "Czechia", iso: "CZ" },
  DNK: { id: "DK", object: "country", name: "Denmark", iso: "DK" },
  ESB: { id: "ESB", object: "country", name: "Dhekelia", iso: "ESB" },
  DJI: { id: "DJ", object: "country", name: "Djibouti", iso: "DJ" },
  DMA: { id: "DM", object: "country", name: "Dominica", iso: "DM" },
  DOM: { id: "DO", object: "country", name: "Dominican Republic", iso: "DO" },
  COD: { id: "CD", object: "country", name: "DR Congo", iso: "CD" },
  ECU: { id: "EC", object: "country", name: "Ecuador", iso: "EC" },
  EGY: { id: "EG", object: "country", name: "Egypt", iso: "EG" },
  SLV: { id: "SV", object: "country", name: "El Salvador", iso: "SV" },
  GNQ: { id: "GQ", object: "country", name: "Equatorial Guinea", iso: "GQ" },
  ERI: { id: "ER", object: "country", name: "Eritrea", iso: "ER" },
  EST: { id: "EE", object: "country", name: "Estonia", iso: "EE" },
  SWZ: { id: "SZ", object: "country", name: "Eswatini", iso: "SZ" },
  ETH: { id: "ET", object: "country", name: "Ethiopia", iso: "ET" },
  EUR: { id: "EU", object: "country", name: "Europe Union", iso: "EU" },
  FLK: { id: "FK", object: "country", name: "Falkland Islands", iso: "FK" },
  FRO: { id: "FO", object: "country", name: "Faroe Islands", iso: "FO" },
  FJI: { id: "FJ", object: "country", name: "Fiji", iso: "FJ" },
  FIN: { id: "FI", object: "country", name: "Finland", iso: "FI" },
  FRA: { id: "FR", object: "country", name: "France", iso: "FR" },
  GUF: { id: "GF", object: "country", name: "French Guiana", iso: "GF" },
  PYF: { id: "PF", object: "country", name: "French Polynesia", iso: "PF" },
  ATF: {
    id: "TF",
    object: "country",
    name: "French Southern and Antarctic Lands",
    iso: "TF",
  },
  GAB: { id: "GA", object: "country", name: "Gabon", iso: "GA" },
  GMB: { id: "GM", object: "country", name: "Gambia", iso: "GM" },
  GEO: { id: "GE", object: "country", name: "Georgia", iso: "GE" },
  DEU: { id: "DE", object: "country", name: "Germany", iso: "DE" },
  GHA: { id: "GH", object: "country", name: "Ghana", iso: "GH" },
  GIB: { id: "GI", object: "country", name: "Gibraltar", iso: "GI" },
  GRC: { id: "GR", object: "country", name: "Greece", iso: "GR" },
  GRL: { id: "GL", object: "country", name: "Greenland", iso: "GL" },
  GRD: { id: "GD", object: "country", name: "Grenada", iso: "GD" },
  GLP: { id: "GP", object: "country", name: "Guadeloupe", iso: "GP" },
  GUM: { id: "GU", object: "country", name: "Guam", iso: "GU" },
  GTM: { id: "GT", object: "country", name: "Guatemala", iso: "GT" },
  GGY: { id: "GG", object: "country", name: "Guernsey", iso: "GG" },
  GIN: { id: "GN", object: "country", name: "Guinea", iso: "GN" },
  GNB: { id: "GW", object: "country", name: "Guinea-Bissau", iso: "GW" },
  GUY: { id: "GY", object: "country", name: "Guyana", iso: "GY" },
  HTI: { id: "HT", object: "country", name: "Haiti", iso: "HT" },
  HMD: {
    id: "HM",
    object: "country",
    name: "Heard Island and McDonald Islands",
    iso: "HM",
  },
  HND: { id: "HN", object: "country", name: "Honduras", iso: "HN" },
  HKG: { id: "HK", object: "country", name: "Hong Kong", iso: "HK" },
  HUN: { id: "HU", object: "country", name: "Hungary", iso: "HU" },
  ISL: { id: "IS", object: "country", name: "Iceland", iso: "IS" },
  IND: { id: "IN", object: "country", name: "India", iso: "IN" },
  IOA: {
    id: "IOA",
    object: "country",
    name: "Indian Ocean Ter.",
    iso: "IOA",
  },
  IDN: { id: "ID", object: "country", name: "Indonesia", iso: "ID" },
  IRN: { id: "IR", object: "country", name: "Iran", iso: "IR" },
  IRQ: { id: "IQ", object: "country", name: "Iraq", iso: "IQ" },
  IRL: { id: "IE", object: "country", name: "Ireland", iso: "IE" },
  IMN: { id: "IM", object: "country", name: "Isle of Man", iso: "IM" },
  ISR: { id: "IL", object: "country", name: "Israel", iso: "IL" },
  ITA: { id: "IT", object: "country", name: "Italy", iso: "IT" },
  CIV: { id: "CI", object: "country", name: "Ivory Coast", iso: "CI" },
  JAM: { id: "JM", object: "country", name: "Jamaica", iso: "JM" },
  JPN: { id: "JP", object: "country", name: "Japan", iso: "JP" },
  JEY: { id: "JE", object: "country", name: "Jersey", iso: "JE" },
  JOR: { id: "JO", object: "country", name: "Jordan", iso: "JO" },
  KAZ: { id: "KZ", object: "country", name: "Kazakhstan", iso: "KZ" },
  KEN: { id: "KE", object: "country", name: "Kenya", iso: "KE" },
  KIR: { id: "KI", object: "country", name: "Kiribati", iso: "KI" },
  UNK: { id: "XK", object: "country", name: "Kosovo", iso: "XK" },
  KWT: { id: "KW", object: "country", name: "Kuwait", iso: "KW" },
  KGZ: { id: "KG", object: "country", name: "Kyrgyzstan", iso: "KG" },
  LAO: { id: "LA", object: "country", name: "Laos", iso: "LA" },
  LVA: { id: "LV", object: "country", name: "Latvia", iso: "LV" },
  LBN: { id: "LB", object: "country", name: "Lebanon", iso: "LB" },
  LSO: { id: "LS", object: "country", name: "Lesotho", iso: "LS" },
  LBR: { id: "LR", object: "country", name: "Liberia", iso: "LR" },
  LBY: { id: "LY", object: "country", name: "Libya", iso: "LY" },
  LIE: { id: "LI", object: "country", name: "Liechtenstein", iso: "LI" },
  LTU: { id: "LT", object: "country", name: "Lithuania", iso: "LT" },
  LUX: { id: "LU", object: "country", name: "Luxembourg", iso: "LU" },
  MAC: { id: "MO", object: "country", name: "Macau", iso: "MO" },
  MDG: { id: "MG", object: "country", name: "Madagascar", iso: "MG" },
  MWI: { id: "MW", object: "country", name: "Malawi", iso: "MW" },
  MYS: { id: "MY", object: "country", name: "Malaysia", iso: "MY" },
  MDV: { id: "MV", object: "country", name: "Maldives", iso: "MV" },
  MLI: { id: "ML", object: "country", name: "Mali", iso: "ML" },
  MLT: { id: "MT", object: "country", name: "Malta", iso: "MT" },
  MHL: { id: "MH", object: "country", name: "Marshall Islands", iso: "MH" },
  MTQ: { id: "MQ", object: "country", name: "Martinique", iso: "MQ" },
  MRT: { id: "MR", object: "country", name: "Mauritania", iso: "MR" },
  MUS: { id: "MU", object: "country", name: "Mauritius", iso: "MU" },
  MYT: { id: "YT", object: "country", name: "Mayotte", iso: "YT" },
  MEX: { id: "MX", object: "country", name: "Mexico", iso: "MX" },
  FSM: { id: "FM", object: "country", name: "Micronesia", iso: "FM" },
  MDA: { id: "MD", object: "country", name: "Moldova", iso: "MD" },
  MCO: { id: "MC", object: "country", name: "Monaco", iso: "MC" },
  MNG: { id: "MN", object: "country", name: "Mongolia", iso: "MN" },
  MNE: { id: "ME", object: "country", name: "Montenegro", iso: "ME" },
  MSR: { id: "MS", object: "country", name: "Montserrat", iso: "MS" },
  MAR: { id: "MA", object: "country", name: "Morocco", iso: "MA" },
  MOZ: { id: "MZ", object: "country", name: "Mozambique", iso: "MZ" },
  MMR: { id: "MM", object: "country", name: "Myanmar", iso: "MM" },
  CYN: { id: "CYN", object: "country", name: "N. Cyprus", iso: "CYN" },
  NAM: { id: "NA", object: "country", name: "Namibia", iso: "NA" },
  NRU: { id: "NR", object: "country", name: "Nauru", iso: "NR" },
  NPL: { id: "NP", object: "country", name: "Nepal", iso: "NP" },
  NLD: { id: "NL", object: "country", name: "Netherlands", iso: "NL" },
  NCL: { id: "NC", object: "country", name: "New Caledonia", iso: "NC" },
  NZL: { id: "NZ", object: "country", name: "New Zealand", iso: "NZ" },
  NIC: { id: "NI", object: "country", name: "Nicaragua", iso: "NI" },
  NER: { id: "NE", object: "country", name: "Niger", iso: "NE" },
  NGA: { id: "NG", object: "country", name: "Nigeria", iso: "NG" },
  NIU: { id: "NU", object: "country", name: "Niue", iso: "NU" },
  NFK: { id: "NF", object: "country", name: "Norfolk Island", iso: "NF" },
  PRK: { id: "KP", object: "country", name: "North Korea", iso: "KP" },
  MKD: { id: "MK", object: "country", name: "North Macedonia", iso: "MK" },
  MNP: {
    id: "MP",
    object: "country",
    name: "Northern Mariana Islands",
    iso: "MP",
  },
  NOR: { id: "NO", object: "country", name: "Norway", iso: "NO" },
  OMN: { id: "OM", object: "country", name: "Oman", iso: "OM" },
  PAK: { id: "PK", object: "country", name: "Pakistan", iso: "PK" },
  PLW: { id: "PW", object: "country", name: "Palau", iso: "PW" },
  PSE: { id: "PS", object: "country", name: "Palestine", iso: "PS" },
  PAN: { id: "PA", object: "country", name: "Panama", iso: "PA" },
  PNG: { id: "PG", object: "country", name: "Papua New Guinea", iso: "PG" },
  PRY: { id: "PY", object: "country", name: "Paraguay", iso: "PY" },
  PER: { id: "PE", object: "country", name: "Peru", iso: "PE" },
  PHL: { id: "PH", object: "country", name: "Philippines", iso: "PH" },
  PCN: { id: "PN", object: "country", name: "Pitcairn Islands", iso: "PN" },
  POL: { id: "PL", object: "country", name: "Poland", iso: "PL" },
  PRT: { id: "PT", object: "country", name: "Portugal", iso: "PT" },
  PRI: { id: "PR", object: "country", name: "Puerto Rico", iso: "PR" },
  QAT: { id: "QA", object: "country", name: "Qatar", iso: "QA" },
  COG: {
    id: "CG",
    object: "country",
    name: "Republic of the Congo",
    iso: "CG",
  },
  REU: { id: "RE", object: "country", name: "R\u00e9union", iso: "RE" },
  ROU: { id: "RO", object: "country", name: "Romania", iso: "RO" },
  RUS: { id: "RU", object: "country", name: "Russia", iso: "RU" },
  RWA: { id: "RW", object: "country", name: "Rwanda", iso: "RW" },
  BLM: {
    id: "BL",
    object: "country",
    name: "Saint Barth\u00e9lemy",
    iso: "BL",
  },
  SHN: {
    id: "SH",
    object: "country",
    name: "Saint Helena, Ascension and Tristan da Cunha",
    iso: "SH",
  },
  KNA: {
    id: "KN",
    object: "country",
    name: "Saint Kitts and Nevis",
    iso: "KN",
  },
  LCA: { id: "LC", object: "country", name: "Saint Lucia", iso: "LC" },
  MAF: { id: "MF", object: "country", name: "Saint Martin", iso: "MF" },
  SPM: {
    id: "PM",
    object: "country",
    name: "Saint Pierre and Miquelon",
    iso: "PM",
  },
  VCT: {
    id: "VC",
    object: "country",
    name: "Saint Vincent and the Grenadines",
    iso: "VC",
  },
  WSM: { id: "WS", object: "country", name: "Samoa", iso: "WS" },
  SMR: { id: "SM", object: "country", name: "San Marino", iso: "SM" },
  STP: {
    id: "ST",
    object: "country",
    name: "S\u00e3o Tom\u00e9 and Pr\u00edncipe",
    iso: "ST",
  },
  SAU: { id: "SA", object: "country", name: "Saudi Arabia", iso: "SA" },
  SCR: { id: "SCR", object: "country", name: "Scarborough Reef", iso: "SCR" },
  SEN: { id: "SN", object: "country", name: "Senegal", iso: "SN" },
  SRB: { id: "RS", object: "country", name: "Serbia", iso: "RS" },
  SER: { id: "SER", object: "country", name: "Serranilla Bank", iso: "SER" },
  SYC: { id: "SC", object: "country", name: "Seychelles", iso: "SC" },
  KAS: { id: "KAS", object: "country", name: "Siachen Glacier", iso: "KAS" },
  SLE: { id: "SL", object: "country", name: "Sierra Leone", iso: "SL" },
  SGP: { id: "SG", object: "country", name: "Singapore", iso: "SG" },
  SXM: { id: "SX", object: "country", name: "Sint Maarten", iso: "SX" },
  SVK: { id: "SK", object: "country", name: "Slovakia", iso: "SK" },
  SVN: { id: "SI", object: "country", name: "Slovenia", iso: "SI" },
  SLB: { id: "SB", object: "country", name: "Solomon Islands", iso: "SB" },
  SOM: { id: "SO", object: "country", name: "Somalia", iso: "SO" },
  SOL: { id: "SOL", object: "country", name: "Somaliland", iso: "SOL" },
  ZAF: { id: "ZA", object: "country", name: "South Africa", iso: "ZA" },
  SGS: { id: "GS", object: "country", name: "South Georgia", iso: "GS" },
  KOR: { id: "KR", object: "country", name: "South Korea", iso: "KR" },
  SSD: { id: "SS", object: "country", name: "South Sudan", iso: "SS" },
  ESP: { id: "ES", object: "country", name: "Spain", iso: "ES" },
  PGA: { id: "PGA", object: "country", name: "Spratly Is.", iso: "PGA" },
  LKA: { id: "LK", object: "country", name: "Sri Lanka", iso: "LK" },
  SDN: { id: "SD", object: "country", name: "Sudan", iso: "SD" },
  SUR: { id: "SR", object: "country", name: "Suriname", iso: "SR" },
  SJM: {
    id: "SJ",
    object: "country",
    name: "Svalbard and Jan Mayen",
    iso: "SJ",
  },
  SWE: { id: "SE", object: "country", name: "Sweden", iso: "SE" },
  CHE: { id: "CH", object: "country", name: "Switzerland", iso: "CH" },
  SYR: { id: "SY", object: "country", name: "Syria", iso: "SY" },
  TWN: { id: "TW", object: "country", name: "Taiwan", iso: "TW" },
  TJK: { id: "TJ", object: "country", name: "Tajikistan", iso: "TJ" },
  TZA: { id: "TZ", object: "country", name: "Tanzania", iso: "TZ" },
  THA: { id: "TH", object: "country", name: "Thailand", iso: "TH" },
  TLS: { id: "TL", object: "country", name: "Timor-Leste", iso: "TL" },
  TGO: { id: "TG", object: "country", name: "Togo", iso: "TG" },
  TKL: { id: "TK", object: "country", name: "Tokelau", iso: "TK" },
  TON: { id: "TO", object: "country", name: "Tonga", iso: "TO" },
  TTO: {
    id: "TT",
    object: "country",
    name: "Trinidad and Tobago",
    iso: "TT",
  },
  TUN: { id: "TN", object: "country", name: "Tunisia", iso: "TN" },
  TUR: { id: "TR", object: "country", name: "Turkey", iso: "TR" },
  TKM: { id: "TM", object: "country", name: "Turkmenistan", iso: "TM" },
  TCA: {
    id: "TC",
    object: "country",
    name: "Turks and Caicos Islands",
    iso: "TC",
  },
  TUV: { id: "TV", object: "country", name: "Tuvalu", iso: "TV" },
  UGA: { id: "UG", object: "country", name: "Uganda", iso: "UG" },
  UKR: { id: "UA", object: "country", name: "Ukraine", iso: "UA" },
  ARE: {
    id: "AE",
    object: "country",
    name: "United Arab Emirates",
    iso: "AE",
  },
  GBR: { id: "GB", object: "country", name: "United Kingdom", iso: "GB" },
  USA: { id: "US", object: "country", name: "United States", iso: "US" },
  UMI: {
    id: "UM",
    object: "country",
    name: "United States Minor Outlying Islands",
    iso: "UM",
  },
  VIR: {
    id: "VI",
    object: "country",
    name: "United States Virgin Islands",
    iso: "VI",
  },
  URY: { id: "UY", object: "country", name: "Uruguay", iso: "UY" },
  USG: {
    id: "USG",
    object: "country",
    name: "USNB Guantanamo Bay",
    iso: "USG",
  },
  UZB: { id: "UZ", object: "country", name: "Uzbekistan", iso: "UZ" },
  VUT: { id: "VU", object: "country", name: "Vanuatu", iso: "VU" },
  VAT: { id: "VA", object: "country", name: "Vatican City", iso: "VA" },
  VEN: { id: "VE", object: "country", name: "Venezuela", iso: "VE" },
  VNM: { id: "VN", object: "country", name: "Vietnam", iso: "VN" },
  WLF: { id: "WF", object: "country", name: "Wallis and Futuna", iso: "WF" },
  ESH: { id: "EH", object: "country", name: "Western Sahara", iso: "EH" },
  YEM: { id: "YE", object: "country", name: "Yemen", iso: "YE" },
  ZMB: { id: "ZM", object: "country", name: "Zambia", iso: "ZM" },
  ZWE: { id: "ZW", object: "country", name: "Zimbabwe", iso: "ZW" },
} as const;
